version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        description: greenweez raw data
        identifier: raw_gz_product
      - name: sales
        description: information regarding our sales
        identifier: raw_gz_sales
        tests: 
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: ship
        description: information regarding our shipping costs
        identifier: raw_gz_ship
      - name: adwords
        description: Info regarding the ad campaigns
        identifier: raw_gz_adwords

      - name: bing
        description: Info regarding the campaign done on Bing
        identifier: raw_gz_bing
      
      - name: criteo
        description: Info regarding the campaign done on Bing
        identifier: raw_gz_criteo

      - name: facebook
        description: Info regarding the campaign done on Bing
        identifier: raw_gz_facebook